# Generated by Django 4.2.6 on 2023-10-24 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=254, verbose_name='Home Title')),
                ('text', models.TextField(verbose_name='Home Text')),
                ('button_name', models.CharField(max_length=254, verbose_name='Home Button Name')),
                ('img', models.ImageField(upload_to='media', verbose_name='Home Image')),
            ],
            options={
                'verbose_name': 'Home',
                'verbose_name_plural': 'Home',
            },
        ),
    ]
