# Generated by Django 4.2.6 on 2023-10-24 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coffee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Coffee Name')),
                ('about', models.TextField(verbose_name='About Coffee')),
                ('img', models.ImageField(upload_to='media', verbose_name='Coffee img')),
            ],
        ),
    ]
