# Generated by Django 4.2.6 on 2023-10-24 07:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_coffee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popular_Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.coffee')),
            ],
            options={
                'verbose_name': 'Popular_Items',
                'verbose_name_plural': 'Popular_Items',
            },
        ),
    ]
