# Generated by Django 4.2.6 on 2023-10-24 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_popular_items_coffee_popular_items_coffee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todays_special',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee', models.ManyToManyField(to='main.coffee')),
            ],
            options={
                'verbose_name': 'Todays_special',
                'verbose_name_plural': 'Todays_special',
            },
        ),
    ]
