# Generated by Django 4.2.6 on 2023-10-24 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_todays_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='Daily_Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media', verbose_name='IMG')),
                ('text', models.TextField(verbose_name='Text')),
                ('about1', models.CharField(max_length=254, verbose_name='about1')),
                ('about2', models.CharField(max_length=254, verbose_name='about2')),
                ('about3', models.CharField(max_length=254, verbose_name='about3')),
                ('about4', models.CharField(max_length=254, verbose_name='about4')),
                ('about5', models.CharField(max_length=254, verbose_name='about5')),
                ('about6', models.CharField(max_length=254, verbose_name='about6')),
            ],
            options={
                'verbose_name': 'Daily_Menu',
                'verbose_name_plural': 'Daily_Menu',
            },
        ),
    ]
