# Generated by Django 4.2.6 on 2023-10-24 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_daily_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Name')),
                ('text', models.TextField(verbose_name='Text')),
                ('img', models.ImageField(upload_to='media', verbose_name='IMG')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
        migrations.RemoveField(
            model_name='home',
            name='button_name',
        ),
    ]
