# Generated by Django 4.2.6 on 2023-10-24 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_menu_remove_home_button_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'verbose_name': 'Menu', 'verbose_name_plural': 'Menu'},
        ),
    ]
