# Generated by Django 4.2.6 on 2023-10-24 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_menu_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
    ]
