# Generated by Django 4.2.6 on 2023-10-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_coffee_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Our_menus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coffee', models.ManyToManyField(to='main.coffee')),
            ],
            options={
                'verbose_name': 'Our_menus',
                'verbose_name_plural': 'Our_menus',
            },
        ),
    ]
