# Generated by Django 4.2.6 on 2023-10-24 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='category',
            field=models.ManyToManyField(to='main.category'),
        ),
    ]
