# Generated by Django 4.2.6 on 2023-10-24 10:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_coffee_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coffee',
            name='category',
        ),
        migrations.AddField(
            model_name='coffee',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.category'),
            preserve_default=False,
        ),
    ]
